### ISSUE TITLE
 "Error  binance {"code":-2015,"msg":"Invalid API-key, IP, or permission " Where I can see full log?

### ISSUE THREAD

**Issue by kokosandim** [CryptoGnome/LickHunterPRO#1]
Where I can see full logs from this tool? I mean log like in the video? With price etc

**Comment by kokosandim** [comment]
I choosed BCH and put key to "settings.py". Maybe I should specify another some information? My key have all permitions

**Comment by kokosandim** [comment]
And I see error
binance {"code":-2015,"msg":"Invalid API-key, IP, or permissions for action, request ip: 1**.**.**.**"}

**Comment by kokosandim** [comment]
how can I fix this?

**Comment by CryptoGnome** [comment]
you need to launch by calling from CMD to keep logs.
this looks like you did not tick the futures box when making the API key on binance
