### ISSUE TITLE
feature: auto-refresh settings when changed (making feeder scripts possible)

### ISSUE THREAD

**Issue by fahrmairm** [CryptoGnome/LickHunterPRO#14]
bot should automatically reload settings when changed/every minute. 
=> you do not need to restart bot when you play with settings
=> it opens up the bot for other people writing scripts modifying the settings based on external factors, e.g. BTC moves big, increase VWAP or auto-remove pumped coins etc. (feeder approach)

**Comment by CryptoGnome** [comment]
Implemented JSON 1.7 for pairs
