### ISSUE TITLE
invalid literal for int() with base 10: '4582.1'

### ISSUE THREAD

**Issue by daisy613** [CryptoGnome/LickHunterPRO#17]
LHP002-profit > 2020-09-24T02:54:10: Check Positions Called
LHP002-profit > 2020-09-24T02:54:10: ALGO/USDT
LHP002-profit > 2020-09-24T02:54:10: Fetch Ticker Called
LHP002-profit > 2020-09-24T02:54:10: Fetch Take Profit Called
LHP002-profit > 2020-09-24T02:54:10: Direction IS LONG
LHP002-profit > 2020-09-24T02:54:10: Cancel TP Orders Called
LHP002-profit > 2020-09-24T02:54:10: Orders Found, Checking More
LHP002-profit > 2020-09-24T02:54:10: invalid literal for int() with base 10: '4582.1'
LHP002-profit > 2020-09-24T02:54:10: Check Positions Called
LHP002-profit > 2020-09-24T02:54:10: ALGO/USDT
LHP002-profit > 2020-09-24T02:54:10: Fetch Ticker Called
LHP002-profit > 2020-09-24T02:54:10: Fetch Take Profit Called
LHP002-profit > 2020-09-24T02:54:10: Direction IS LONG
LHP002-profit > 2020-09-24T02:54:10: Cancel TP Orders Called
LHP002-profit > 2020-09-24T02:54:10: Orders Found, Checking More
LHP002-profit > 2020-09-24T02:54:10: invalid literal for int() with base 10: '4582.1'
LHP002-profit > 2020-09-24T02:54:10: Check Positions Called
LHP002-profit > 2020-09-24T02:54:10: ALGO/USDT
LHP002-profit > 2020-09-24T02:54:10: Fetch Ticker Called
LHP002-profit > 2020-09-24T02:54:10: Fetch Take Profit Called
LHP002-profit > 2020-09-24T02:54:10: Direction IS LONG
LHP002-profit > 2020-09-24T02:54:10: Cancel TP Orders Called
LHP002-profit > 2020-09-24T02:54:10: Orders Found, Checking More
LHP002-profit > 2020-09-24T02:54:10: invalid literal for int() with base 10: '4582.1'

**Comment by doosjenever** [comment]
I have the same issue and no new orders are placed, have two open positions: ERROR - 2020-10-14 20:54:10,468 - invalid literal for int() with base 10: '0.067'

**Comment by CryptoGnome** [comment]
is this still an issue?

**Comment by doosjenever** [comment]
On 1.6 i had this issue 2 days ago

**Comment by CryptoGnome** [comment]
need more details, not really sure what part is causing this yet
