### ISSUE TITLE
Feature Requests - Automated VWAP offset - Multiple Pairs - HODL when inactive

### ISSUE THREAD

**Issue by RowSalmon** [CryptoGnome/LickHunterPRO#2]
1. Automated VWAP offset changes based on Volatility to enable better, more precise entry points. One might use ADX to automate this.

2. Multiple Pairs being simultaneously watched/traded at the same time. This can increase the amount of liquidations available to be capitalized on. Each asset would have it's own vwap settings and the bot would only catch a single asset's liquidation at a time thus preventing the bot's capital from being spread too thin across multiple assets.

3. The ability to have assets in a HODL trade when vwap is not above or below the offsets instead of USDT. This will enable the bot both capitalize on liquidations whilst simultaneously catching the movements of another long term asset. For instance, I might hold ADA when the bot is in the vwap range and move to USDT when it is above or below the vwap range.

**Comment by RowSalmon** [comment]
4. Community development or the ability to make addons. This could enable faster development of features as well as result in a far more comprehensive and capable bot. I know I would personally be down to do development for the bot.

**Comment by CryptoGnome** [comment]
Added #3

**Comment by CryptoGnome** [comment]
https://github.com/daisy613/LHPControl/releases/tag/v1.77.0f
