### ISSUE TITLE
Bot triggers an order to the opposite direction despite having an open position

### ISSUE THREAD

**Issue by santanicholass** [CryptoGnome/LickHunterPRO#21]
I noticed where the bot triggers an order in an opposite direction despite having an open position. This usually occurs when im keeping an open long position for days during a massive dump, the vwap then gets resseted the following day, now if the coin pumps passes the vwap offset, instead of waiting to hit the TP of the long position first, the bot will immediately try to open a short position resulting in settling some of my position with a loss.

**Comment by CryptoGnome** [comment]
this is by design, it starts to reduce the position if it is not closed yet
