### ISSUE TITLE
bybit {"ret_code":20006,"ret_msg":"symbol is not in the range of selected","ext_code":"","result":null,"ext_info":null,"time_now":"1603982435.117794","rate_limit_status":74,"rate_limit_reset_ms":1603982435180,"rate_limit":75}

### ISSUE THREAD

**Issue by Mike454545** [CryptoGnome/LickHunterPRO#22]
I get this error code over and over seems like right when it's going to place an order
bybit {"ret_code":20006,"ret_msg":"symbol is not in the range of selected","ext_code":"","result":null,"ext_info":null,"time_now":"1603982435.117794","rate_limit_status":74,"rate_limit_reset_ms":1603982435180,"rate_limit":75}
there's also some kind of websocket error asking to update websocket api to 1.26.0
![Capture](https://user-images.githubusercontent.com/73655283/97591315-df4c9a80-19d5-11eb-8ef4-319a9b320830.JPG)

**Comment by Mike454545** [comment]
no order was ever sent to bybit either.

**Comment by CryptoGnome** [comment]
error in settings file this is fixed in 1.7
