### ISSUE TITLE
The exe files are identified as a trojan by several AV engines

### ISSUE THREAD

**Issue by autrion** [CryptoGnome/LickHunterPRO#25]
See: https://www.virustotal.com/gui/file/dfb1907815d7158d153b843ad60bd59a12f2e4a52128858abcaa0bb987b482bc/behavior

**Comment by autrion** [comment]
https://www.virustotal.com/gui/file/dfb1907815d7158d153b843ad60bd59a12f2e4a52128858abcaa0bb987b482bc/detection

**Comment by CryptoGnome** [comment]
False Positive, visit the discord others can confirm
