### ISSUE TITLE
"code":-4061,"msg":"Order's position side does not match user's setting."

### ISSUE THREAD

**Issue by brucorp1** [CryptoGnome/LickHunterPRO#29]
Hello,
what can it be?
binance {"code":-4061,"msg":"Order's position side does not match user's setting."}  
binanceWebsocket > Starting Loop...      
binanceWebsocket > Launching Liquidation Websocket...

percentBal = 0.2
maxPosition = 30
maxOpen = 10

leverage = 10

lick_value = 500

check_licks = False

Regards.

**Comment by CryptoGnome** [comment]
any more info on this?
please update

**Comment by brucorp1** [comment]
> any more info on this?
> please update

When i switch to one-way mode, everything it's ok. Sorry :)

**Comment by 82bladerunner** [comment]
> > any more info on this?
> > please update
> 
> When i switch to one-way mode, everything it's ok. Sorry :)

Where do you configure the mode?
