### ISSUE TITLE
binance does not have market symbol 

### ISSUE THREAD

**Issue by erikveenhuis** [CryptoGnome/LickHunterPRO#30]
since a couple of hours ago the error log is full of these:

ERROR - 2020-11-10 02:38:48,703 - binance does not have market symbol BTC/USDT
ERROR - 2020-11-10 02:40:09,467 - binance does not have market symbol ETH/USDT
ERROR - 2020-11-10 02:40:11,828 - binance does not have market symbol SXP/USDT
ERROR - 2020-11-10 02:41:38,483 - binance does not have market symbol XTZ/USDT
ERROR - 2020-11-10 02:45:44,516 - binance does not have market symbol SNX/USDT
ERROR - 2020-11-10 02:46:57,515 - binance does not have market symbol ALGO/USDT
ERROR - 2020-11-10 02:47:25,157 - binance does not have market symbol VET/USDT
ERROR - 2020-11-10 02:47:27,468 - binance does not have market symbol BNB/USDT
ERROR - 2020-11-10 02:47:29,156 - binance does not have market symbol XTZ/USDT
ERROR - 2020-11-10 02:47:31,131 - binance does not have market symbol ALGO/USDT
ERROR - 2020-11-10 02:47:34,358 - binance does not have market symbol LINK/USDT
ERROR - 2020-11-10 02:47:39,436 - binance does not have market symbol ETH/USDT
ERROR - 2020-11-10 02:47:45,343 - binance does not have market symbol LINK/USDT
ERROR - 2020-11-10 02:47:55,530 - binance does not have market symbol ETH/USDT
ERROR - 2020-11-10 02:48:01,312 - binance does not have market symbol VET/USDT

**Comment by CryptoGnome** [comment]
resolved #
