### ISSUE TITLE
Binance does not have market symbol BTC/USDT

### ISSUE THREAD

**Issue by AtsutaneDotNet** [CryptoGnome/LickHunterPRO#31]
![1 72 problem](https://user-images.githubusercontent.com/6040550/98703364-61fe2e00-23b6-11eb-9dd1-c3fe8e1c1e79.PNG)
![1 72 default coins](https://user-images.githubusercontent.com/6040550/98703392-675b7880-23b6-11eb-93f2-3bcf97c1cef9.PNG)
 Out of suddent the bot suddenly not working. Try fresh installation also not work

**Comment by AtsutaneDotNet** [comment]
USER AUTHENTICATED!
Starting Loop...
Launching Liquidation Websocket...
LINK Lick Value $USD not above Min Value $  500

LINK 
Lick Value $USD not above Min Value $  500
RSR Lick Value $USD not above Min Value $  500
AAVE Lick Value $USD not above Min Value $  500

AAVE Lick Value $USD not above Min Value $  500

----------------------------------
# of Contracts:  37.6
Lick Size $USD:  2402.6776000000004
Lick Symbol:
AAVE
Lick Side:  SELL
Time =  1605022710520
----------------------------------
Fetch Ticker Called
AAVE/USDT

binance does not have market symbol AAVE/USDT

Starting Loop...

Launching Liquidation Websocket...

**Comment by CryptoGnome** [comment]
resolved
