### ISSUE TITLE
Settings.json not found

### ISSUE THREAD

**Issue by Xeckin** [CryptoGnome/LickHunterPRO#33]
Unzipped 1.74 and input keys and values in settings.json.  Upon start up I get this error:
![image](https://user-images.githubusercontent.com/73088071/98893764-34c28600-2471-11eb-9752-6bbb464b10c4.png)

This is the the directory structure:
![image](https://user-images.githubusercontent.com/73088071/98893811-558adb80-2471-11eb-86d0-881d03e39aac.png)

ERROR text for reference:
binanceProfit >   File "binanceProfit.py", line 12, in <module>
binanceProfit > FileNotFoundError: [Errno 2] No such file or directory: '../settings.json'
binanceProfit > [888] Failed to execute script binanceProfit

**Comment by erikveenhuis** [comment]
Have you tried copying the settings + coins to /binance/ folder?
