### ISSUE TITLE
Multiple Errors, bot sometimes dosnt open any trades but Bot Monitor shows nothing wrong.

### ISSUE THREAD

**Issue by L0Y4L** [CryptoGnome/LickHunterPRO#34]
So from the Websocketlog I get these:

CRITICAL - 2020-11-12 02:32:51,194 - BinanceWebSocketApiSocket.start_socket(50ea59ee-eed1-4f7d-9d47-1ea95410e43f, ['!forceOrder'], ['{}']) - Exception ConnectionClosed - error_msg: code = 1006 (connection closed abnormally [internal]), no reason
CRITICAL - 2020-11-12 02:32:51,194 - BinanceWebSocketApiManager.stream_is_crashing(50ea59ee-eed1-4f7d-9d47-1ea95410e43f)

And also this one "ERROR - 2020-11-12 06:02:01,646 - binance {"code":-4003,"msg":"Quantity less than zero."}"

and from my Profit log its this:

ERROR - 2020-11-12 06:01:02,639 - binance {"code":-2022,"msg":"ReduceOnly Order is rejected."}

Hope you can help me out :)
[binanceProfitError.log](https://github.com/CryptoGnome/LickHunterPRO/files/5531059/binanceProfitError.log)
[binanceWebsocketError.log](https://github.com/CryptoGnome/LickHunterPRO/files/5531060/binanceWebsocketError.log)

**Comment by CryptoGnome** [comment]
These can all be ignored.

And also this one "ERROR - 2020-11-12 06:02:01,646 - binance {"code":-4003,"msg":"Quantity less than zero."}"
^ This means you are trying to submit an order that as less than the exchange min
