### ISSUE TITLE
Version 1.74 - Bybit dca settings have no effect

### ISSUE THREAD

**Issue by ninjaWhippet** [CryptoGnome/LickHunterPRO#35]
I have been testing bybit on version 1.74, the order size (pb), VWAP, TP, etc all work ok for both ETH and BTC (running concurrently on the same bot).

I have noticed that order size does not change regardless of when price exceeds the set dcaone and dcatwo threshold (so it looks like the dca function is not working on bybit), orders reman at 1 x percbal and not multiplied by the relevant factor as expected. This occurred with the below dca settings:

dcaOne = 1
Factorone = 2
dcaTwo = 5
factorTwo = 3

I haven't tried this on binance to confirm whether its a common bug to the bot or just specific to the bybit exchange.

Thanks.

**Comment by CryptoGnome** [comment]
Can anyone confirm this with more data?

**Comment by ninjaWhippet** [comment]
Please close, it is no longer occurring and I haven't been able to replicate this since
