### ISSUE TITLE
Version 1.75: No webhook for long liquidation

### ISSUE THREAD

**Issue by AtsutaneDotNet** [CryptoGnome/LickHunterPRO#36]
At the current moment, when there is long liquidation event. The bot no longer show webhook for long liquidation. It work fine on short liquidation. Checking websocket error log nothing found related to websocket error.

The same issue also have been reported in channel by "Crypto Monkey"

**Comment by santanicholass** [comment]
Noticed the same issue.

**Comment by CryptoGnome** [comment]
fixed for next release
