### ISSUE TITLE
Version 1.75: Bot do not reload settings.json

### ISSUE THREAD

**Issue by AtsutaneDotNet** [CryptoGnome/LickHunterPRO#37]
![CG say yes](https://user-images.githubusercontent.com/6040550/101269008-a3f77580-37a4-11eb-95f1-e394f8490daa.PNG)

Try to change the settings.json while the bot running (Changing leverage, percentBal, Take Profit) and the change do not take effect until the bot is restarted.

Is the behaviour correct?

**Comment by CryptoGnome** [comment]
did you save the file?

**Comment by CryptoGnome** [comment]
fixes in 1.76
