### ISSUE TITLE
1.76 don't open orders on ETH ByBit

### ISSUE THREAD

**Issue by Unlimitmood** [CryptoGnome/LickHunterPRO#38]
as you see on screen, when licks occurred bot don't sent orders to open position even if USD value of lick is 4877$ with my LH settings 500$ . VWAP was ok on this level.
<img width="618" alt="Снимок экрана 2020-12-08 в 17 32 14" src="https://user-images.githubusercontent.com/32781534/101642603-2ed4ac00-3a01-11eb-9226-aca464dd80b3.png">

**Comment by tinof** [comment]
Having the same problem, how did you fix this?
