### ISSUE TITLE
1.77 bybitProfix.exe has errors and doesnt set TP orders

### ISSUE THREAD

**Issue by r00tlagger** [CryptoGnome/LickHunterPRO#39]
websocket works fine. Positions are open but bybitProfit has errors, doesnt set TP and therefore doesnt take profit.

https://i.imgur.com/PPVTWSC.png

I had to manually close the positions. I know of one other member who has the same issues.
Rebooting the machine didnt help.

**Comment by Deadly-M** [comment]
Same problem here, also on previous few releases it would close my EOS orders immediatly regardless of profit/losss

**Comment by ninjaWhippet** [comment]
It looks like its trying to use binanceprofit instead of bybit profit (even though itds labelledbybitprofit). I saw it raises a bunch of errors as if the coin label is incorrect and creates a binanceprofit.log file (hopefully this helps pin point the issue)
