### ISSUE TITLE
error problem

### ISSUE THREAD

**Issue by parames3010** [CryptoGnome/LickHunterPRO#40]
hello, how to fix this error?
![image](https://user-images.githubusercontent.com/8073243/103157286-e92b2800-47e3-11eb-87cc-e39de7c85695.png)

![image](https://user-images.githubusercontent.com/8073243/103157305-0e1f9b00-47e4-11eb-8856-50ab5bf16e0d.png)

**Comment by CryptoGnome** [comment]
This means you do not have the right permisson enabled on your key, most likely you need to enable futures
