### ISSUE TITLE
Wrong DCA order size picked

### ISSUE THREAD

**Issue by MrPIvanov** [CryptoGnome/LickHunterPRO#42]
Sometimes the bot pick wrong order size when placing orders.
My DCA settings are:
![image](https://user-images.githubusercontent.com/32393652/103748432-c7644900-500c-11eb-90b7-51f9235a3229.png)
This all happen on -40% PNL and all orders need to be dcaTwo( x6 size ( 65-66XLM ))
On biger price placing "normal" order after that the price move close to my entry and start placing DCA orders
![image](https://user-images.githubusercontent.com/32393652/103748336-a56ac680-500c-11eb-91fc-24f2fe592846.png)
Here again on biger price normal order after that dcaTwo order
![image](https://user-images.githubusercontent.com/32393652/103752052-dd283d00-5011-11eb-9839-b1467ec06965.png)

I have a lot more axamples if needed.

Also i know i use LHPC GUI, but this are the active settings from the json file
![image](https://user-images.githubusercontent.com/32393652/103749158-cda6f500-500d-11eb-8fe3-040d67ab1c04.png)

One more Adition. I notice it happens more when the trade is more than -40-50% PNL.
This is a good example of that. DCA working and suddenly stop working and start placing normal orders.
![image](https://user-images.githubusercontent.com/32393652/103890555-f05e0a00-50f0-11eb-9a9d-3386a7d7c8e7.png)

**Comment by CryptoGnome** [comment]
This is a LHCP bug please post on the proper Github

**Comment by MrPIvanov** [comment]
My thinking was that LHPC is only to change settings and is not responsible for the order size or trading in any way.
When i check manually settings.json they are correct.

**Comment by daisy613** [comment]
Nothing to do with LHPC. It only changes the settings.json file.
