### ISSUE TITLE
Stop loss is broken on Bybit

### ISSUE THREAD

**Issue by hawk-239** [CryptoGnome/LickHunterPRO#44]
Looks like stop-loss is broken on Bybit. If necessary I've screened the trade log and position on chart, but probably the following excerpt from the bybitProfit-out.log would be enough:

Check Positions Called
Checking Direction
Entry Price: 1287.58749559
Fetch Take Profit Called
Direction IS Short
Fetch Ticker Called
Ticker Last: 1295.35
Checking For Open Take Profit
Orders Found, Checking More
Take Profit is up to Date Passing.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Stop Loss Triggered - Market Closing Position.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
binance does not have market symbol ETH/USD

Given what the last line says, it seems like it tried to close it but failed (non-migrated code from binance version?)

**Comment by CryptoGnome** [comment]
hmmm, this should be the correct symbol it is what the other orders use
