### ISSUE TITLE
Buy orders mixed between PB and DCA amounts (double spending)

### ISSUE THREAD

**Issue by Aesgan** [CryptoGnome/LickHunterPRO#46]
Noticed that the bot will open more PB amount buys when a liq comes as well as a DCAONE amount buy mixed together.
https://cdn.discordapp.com/attachments/685258964266647564/798936921496879154/Screenshot_20210113_152955.jpg

My balance is 4707$, pb is 0.07 and dcaOne is 0.5, with factorOne 2. dcaTwo is 1.75 and factorTwo is 4.

**Comment by MrPIvanov** [comment]
I have the same problem. Sometimes even the bot picks only pb orders when dcaTwo orders are needed.

**Comment by CryptoGnome** [comment]
Found bug will push release with fix
