### ISSUE TITLE
Adjustable log level and multiple log files

### ISSUE THREAD

**Issue by LeonSpors** [CryptoGnome/LickHunterPRO#49]
I would like to see two enhancements. At the moment the logging is not quite good at all. It would be much better if you could adjust the logging level and if there would be one log file per day. The adjustment could be thru the settings file and/or a start argument.
It makes it much more organized.

**Comment by CryptoGnome** [comment]
so reduced logging size?

**Comment by LeonSpors** [comment]
Yes reduced logging size for normal logging. The current logging could be the verbose mode if you want. And normal logging could be errors and orders only.

**Comment by CryptoGnome** [comment]
https://github.com/daisy613/LHPControl/releases/tag/v1.77.0f
