### ISSUE TITLE
problems with bybit websockets.

### ISSUE THREAD

**Issue by eu20visitar** [CryptoGnome/LickHunterPRO#5]
[bybitWebsocketError.log](https://github.com/CryptoGnome/LickHunterPRO/files/5159207/bybitWebsocketError.log)
[bybitWebsocketError.log](https://github.com/CryptoGnome/LickHunterPRO/files/5159122/bybitWebsocketError.log)
After starting the start profit and start websockets, the program runs normally and if i remove the SL, the bot puts again. 
the problem is after i whiles start to give some errors in .txt file. and sometimes on bot monitor.
![websocket monitor](https://user-images.githubusercontent.com/58561728/91913109-b8f7d080-ecac-11ea-9f48-a6619d57d877.PNG)

as u can see sometimes it works. but takes a lot of time to show on bot monitor.

i uploaded again the file. because the errors appear again.

**Comment by CryptoGnome** [comment]
Seems fine no restarts... this will only scroll if there is a liquidation.
Do you have some other error to report?
