### ISSUE TITLE
DCA not working properly

### ISSUE THREAD

**Issue by drtytrggr** [CryptoGnome/LickHunterPRO#54]
Today 01.02.2021 with XRP

initial buy in 
![image](https://user-images.githubusercontent.com/77405283/106436906-55e9b000-647d-11eb-8d91-5d6dd58796b4.png)

DCA kickin' in
![image](https://user-images.githubusercontent.com/77405283/106436956-6732bc80-647d-11eb-88da-0f4622440718.png)

DCA micin with 1/2 pb buy's
![image](https://user-images.githubusercontent.com/77405283/106437121-99441e80-647d-11eb-97f9-77b4927ef897.png)

Last of the DCA before stopping bot at the time PNL was -20%

![image](https://user-images.githubusercontent.com/77405283/106437187-ad881b80-647d-11eb-954e-8df2063bf0e3.png)

LHPC LOGS
[binanceProfit.log](https://github.com/CryptoGnome/LickHunterPRO/files/5902966/binanceProfit.log)
[binanceWebsocketError.log](https://github.com/CryptoGnome/LickHunterPRO/files/5902970/binanceWebsocketError.log)

rest of the logs were too big to upload (10mb)

**Comment by CryptoGnome** [comment]
what are your DCA levels

**Comment by drtytrggr** [comment]
![image](https://user-images.githubusercontent.com/77405283/106569682-898c0f00-653d-11eb-8338-fbdfe889aa2d.png)

It came in my mind that if the price of coin went too much up and thats why it bought smaller amount?

**Comment by CryptoGnome** [comment]
#53
