### ISSUE TITLE
Manual trades of blacklisted/non-whitelisted coins results a corrupt coins.json

### ISSUE THREAD

**Issue by LeonSpors** [CryptoGnome/LickHunterPRO#55]
Version: 1.80
Affected trading modes: 2-3

If you open a trade of a blacklisted/non-whitelisted coin by yourself, its getting added to _coins.json_. As a result of this behavior is that lickhunter trades the coins after it got closed.

In some cases the bot stops trading other coins.

**Comment by CryptoGnome** [comment]
This is not a Lick Hunter option perhaps you mean LHPC?
