### ISSUE TITLE
Bot Open ETHUSDT Quarterly and not ETHUSDT Perpetual

### ISSUE THREAD

**Issue by AtsutaneDotNet** [CryptoGnome/LickHunterPRO#57]
Using LHPC: No
LickHunterPro: 1.81

Binance release new USD-M Quarterly pair today [https://www.binance.com/en/support/announcement/3309b7d67f024da1b2d8e5a22e476d65](https://www.binance.com/en/support/announcement/3309b7d67f024da1b2d8e5a22e476d65)

Ever since the release, everytime the bot detecting ETH liquidation it open ETHUSDT Quarterly and not ETHUSDT Perpetual.

```
No Position for ETH
Current PNL % 0
LONG ORDER CALLED
Setting Leverage ETH
Long Order Placed
```

![ETHQ](https://user-images.githubusercontent.com/6040550/106914909-6ed5b800-6740-11eb-9747-394f0c23021d.PNG)

Got this error from profit bot but nothing on websocket bot.

```
ERROR - 2021-02-04 23:05:50,254 - binance does not have market symbol ETH_210326/USDT
ERROR - 2021-02-04 23:05:51,254 - binance does not have market symbol ETH_210326/USDT
ERROR - 2021-02-04 23:05:52,238 - binance does not have market symbol ETH_210326/USDT
ERROR - 2021-02-04 23:05:53,223 - binance does not have market symbol ETH_210326/USDT
ERROR - 2021-02-04 23:05:54,316 - binance does not have market symbol ETH_210326/USDT
ERROR - 2021-02-04 23:05:55,270 - binance does not have market symbol ETH_210326/USDT
```

**Comment by unplugged8** [comment]
Hi guys!

I can confirm that my did too open ETH Quarterly and with 20x leverage!!! All my coins are set to 4x. I don't even know where did it take the settings from?!

![eth_quarterly](https://user-images.githubusercontent.com/77389165/108852716-df545400-75dd-11eb-9b9b-02e0eb5f2f9d.jpg)

I had to put ETH on Blacklist...

Thanks

**Comment by daisy613** [comment]
Same thing happening here. I have to close it manually everytime.
