### ISSUE TITLE
Binance LHPC V1.80 market sell in a loss without reach settings

### ISSUE THREAD

**Issue by Green1974** [CryptoGnome/LickHunterPRO#59]
Binance version V1.80 issu with DogeUsdt position 4 febr 2021 07.49 UTC after reaching 75% balance size position closed in a loss without reaching settings.

Max pos  100
Stop loss 7

**Comment by Amannda123** [comment]
Whats your leverage? depending on your settings you probably got either liqudiated or stopped out ..
