### ISSUE TITLE
error on v1.51

### ISSUE THREAD

**Issue by ichieff** [CryptoGnome/LickHunterPRO#6]
im getting this error every day
![unknown (1)](https://user-images.githubusercontent.com/70648249/91994904-0e74c180-ed2f-11ea-8044-de12931ed60a.png)
![image0](https://user-images.githubusercontent.com/70648249/91994909-0f0d5800-ed2f-11ea-9fad-21065ae3a4f9.png)

**Comment by daisy613** [comment]
Same here, as of this morning.

**Comment by CryptoGnome** [comment]
Seems as if the websocket is restarting and the bot is still running right?

**Comment by CryptoGnome** [comment]
I do not see a restart in PM2 which is good as long as the bot is still running

**Comment by ichieff** [comment]
Bot is not running it stopped after this error

**Comment by ichieff** [comment]
bot its show running but not
