### ISSUE TITLE
LickHunterPRO v1.82 closed position at a loss

### ISSUE THREAD

**Issue by teedog932** [CryptoGnome/LickHunterPRO#63]
I had a BLZUSDT short position open when LickHunter started calling long orders for the same symbol causing my short position to be partially sold off at a loss.  So, rather than the profit.exe closing the position it was the websocket.exe causing the position to be sold off when making the long calls while I was still in a short.

![BLZ](https://user-images.githubusercontent.com/53673208/110014855-e4ee2000-7ce8-11eb-9055-7c8a47ddf7c7.JPG)

[binance-LHP001z-W_out.zip](https://github.com/CryptoGnome/LickHunterPRO/files/6086033/binance-LHP001z-W_out.zip)

**Comment by teedog932** [comment]
I added the rest of the output files in a zipped folder.

[save.zip](https://github.com/CryptoGnome/LickHunterPRO/files/6086277/save.zip)

**Comment by CryptoGnome** [comment]
It does this by design atm, it causes the position to slim down naturally
