### ISSUE TITLE
Stop loss not working

### ISSUE THREAD

**Issue by tobintax** [CryptoGnome/LickHunterPRO#65]
Hi, 

thanks for sharing the bot with the community. It seems that the stop loss limit is not working correct. I've set it to the value 10, but the bot keeps buying and I lost a big quantity yesterday and today with the chilli coin. As you can see on my screenshot, I was way above 10%. Or do I use the stop loss limit wrong?

![image](https://user-images.githubusercontent.com/31103804/110349176-be0a5380-8032-11eb-9ca5-4685461e8364.png)

**Comment by unplugged8** [comment]
If the entry price is 0,16874 and you've set SL at 10, the SL would be triggered at 0.185614, no? Mark price is only at the 0.18136 so you have a loooooong way to SL....

**Comment by tobintax** [comment]
that makes sense, i forgot the leverage effect. Sorry for that
