### ISSUE TITLE
Feature Request - DCA Improvements [Risk Management Improvements]

### ISSUE THREAD

**Issue by Oseriduun** [CryptoGnome/LickHunterPRO#69]
As it stands right now, lhp dca is only limited by the maxPos..

It would be a huge improvement to the bot, if the dca was more restrictive..

- Increase the number of dca options
- Limit how many times a particular factor could be executed.
- Add a dca deadzone (doesn't dca below this point.)
- Possibly add a minimum lick value to the dca settings, so that you could customize further when the bot dca's

Often i've had the dca max out my position in the first 1-2% of drawdown, and left me stranded waiting for a reversal.  these changes would be huge improvements to the safety of people using lhp.

**Comment by letsbotit** [comment]
Absolutely !!!

I keep exhausting my maxPos every now and th at just under 2% drawdown
then position is stuck
