### ISSUE TITLE
v1.6 Bybit Bot "Failed to execute script"

### ISSUE THREAD

**Issue by cryptroid** [CryptoGnome/LickHunterPRO#8]
I have installed the bot half a dozen times now thinking maybe I did something wrong, or out of order, etc.  I have done it to the spec of the wiki and the video Gnome made.  For some reason, after I run the Bot Monitor and start the profit and WebSocket it shows me this error in the bot (see screenshot below).  I would post the error log but that isn't working either.  It doesn't report anything, it creates the error file but when I open it in notepad it is blank.  Also, the file that it creates for Bybit is named BinanceProfitError and BybitWebsocketError instead of it saying BybitProfitError, so it makes me think something is messed up and the bot somewhere along the lines thinks it's connecting to Binance not Bybit.  I edited all the executable files and replaced them with the proper directory and file name as seen in the other below screenshots.  I copied the settings file over into each folder as well.  

I was told numerous times to provide a log file but as you can see below in the screenshots, the error log is improperly named when it is created and there is nothing in it when you open it...

<img width="1673" alt="Screen Shot 2020-09-02 at 12 36 48 PM" src="https://user-images.githubusercontent.com/35219101/92011369-fa25ca00-ed18-11ea-9ab2-248fba1bb0a6.png">

<img width="511" alt="Screen Shot 2020-09-02 at 12 35 39 PM" src="https://user-images.githubusercontent.com/35219101/92011258-d1053980-ed18-11ea-836a-8f078804036a.png">

<img width="870" alt="Screen Shot 2020-09-02 at 12 34 06 PM" src="https://user-images.githubusercontent.com/35219101/92011107-98fdf680-ed18-11ea-8cc6-cbbb182484be.png">

<img width="424" alt="Screen Shot 2020-09-02 at 12 34 26 PM" src="https://user-images.githubusercontent.com/35219101/92011139-a4e9b880-ed18-11ea-936b-d81473070ee0.png">

<img width="837" alt="Screen Shot 2020-09-02 at 12 33 48 PM" src="https://user-images.githubusercontent.com/35219101/92011080-8e436180-ed18-11ea-92ea-6bbbfdc35f5b.png">

<img width="831" alt="Screen Shot 2020-09-02 at 12 33 22 PM" src="https://user-images.githubusercontent.com/35219101/92011031-7f5caf00-ed18-11ea-9745-e4c23ee24618.png">

<img width="778" alt="Screen Shot 2020-09-02 at 12 32 13 PM" src="https://user-images.githubusercontent.com/35219101/92010893-563c1e80-ed18-11ea-94f8-52701d1acd5a.png">

<img width="702" alt="Screen Shot 2020-09-01 at 10 20 07 PM" src="https://user-images.githubusercontent.com/35219101/92010446-d3b35f00-ed17-11ea-8431-ef31acaac94d.png">

**Comment by CryptoGnome** [comment]
Please Make PM2 monitor FULLSCREEN then retake that screenshot at the bottom

**Comment by cryptroid** [comment]
Windows command prompt or powershell do not allow you to full screen, you can "maximize but it only maximizes to the size I provided you.   The option to switch the console to "legacy mode" in order to alt+enter and full screen it does not exist on this VPS.

**Comment by cryptroid** [comment]
This is large as I can get the console window by editing the settings.  Full Screen is not an option.

<img width="1670" alt="Screen Shot 2020-09-02 at 1 53 33 PM" src="https://user-images.githubusercontent.com/35219101/92018849-b5536080-ed23-11ea-8b7c-4c5a84feae7a.png">

**Comment by CryptoGnome** [comment]
Did you edit both settings files & what did you enter for pairs

**Comment by ghost** [comment]
I had this same error as well. Until I expanded the screen, per CrytpoGnome's previous request.
Then I was able to see this error message.
![image](https://user-images.githubusercontent.com/30410332/97788210-4ceaf900-1b85-11eb-9830-85c360765479.png)

This looks to be a typical timestamp issue.

**Comment by ghost** [comment]
Sure enough, once I fixed my time sync per your instructions AND also disabled my VPS time sync, this worked fine.
